# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Users/miketerentyev/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.4588.63/CLion.app/Contents/bin/cmake/mac/bin/cmake"

# The command to remove a file.
RM = "/Users/miketerentyev/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.4588.63/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/miketerentyev/itmo/2-year/MegaFinder

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/miketerentyev/itmo/2-year/MegaFinder

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Users/miketerentyev/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.4588.63/CLion.app/Contents/bin/cmake/mac/bin/cmake" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"/Users/miketerentyev/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.4588.63/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/miketerentyev/itmo/2-year/MegaFinder/CMakeFiles /Users/miketerentyev/itmo/2-year/MegaFinder/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/miketerentyev/itmo/2-year/MegaFinder/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named go

# Build rule for target.
go: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 go
.PHONY : go

# fast build rule for target.
go/fast:
	$(MAKE) -f CMakeFiles/go.dir/build.make CMakeFiles/go.dir/build
.PHONY : go/fast

#=============================================================================
# Target rules for targets named frdupl

# Build rule for target.
frdupl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frdupl
.PHONY : frdupl

# fast build rule for target.
frdupl/fast:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/build
.PHONY : frdupl/fast

#=============================================================================
# Target rules for targets named go_autogen

# Build rule for target.
go_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 go_autogen
.PHONY : go_autogen

# fast build rule for target.
go_autogen/fast:
	$(MAKE) -f CMakeFiles/go_autogen.dir/build.make CMakeFiles/go_autogen.dir/build
.PHONY : go_autogen/fast

#=============================================================================
# Target rules for targets named frdupl_autogen

# Build rule for target.
frdupl_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frdupl_autogen
.PHONY : frdupl_autogen

# fast build rule for target.
frdupl_autogen/fast:
	$(MAKE) -f CMakeFiles/frdupl_autogen.dir/build.make CMakeFiles/frdupl_autogen.dir/build
.PHONY : frdupl_autogen/fast

dirlist.o: dirlist.cpp.o

.PHONY : dirlist.o

# target to build an object file
dirlist.cpp.o:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/dirlist.cpp.o
.PHONY : dirlist.cpp.o

dirlist.i: dirlist.cpp.i

.PHONY : dirlist.i

# target to preprocess a source file
dirlist.cpp.i:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/dirlist.cpp.i
.PHONY : dirlist.cpp.i

dirlist.s: dirlist.cpp.s

.PHONY : dirlist.s

# target to generate assembly for a file
dirlist.cpp.s:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/dirlist.cpp.s
.PHONY : dirlist.cpp.s

fileindexer.o: fileindexer.cpp.o

.PHONY : fileindexer.o

# target to build an object file
fileindexer.cpp.o:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/fileindexer.cpp.o
.PHONY : fileindexer.cpp.o

fileindexer.i: fileindexer.cpp.i

.PHONY : fileindexer.i

# target to preprocess a source file
fileindexer.cpp.i:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/fileindexer.cpp.i
.PHONY : fileindexer.cpp.i

fileindexer.s: fileindexer.cpp.s

.PHONY : fileindexer.s

# target to generate assembly for a file
fileindexer.cpp.s:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/fileindexer.cpp.s
.PHONY : fileindexer.cpp.s

frdupl_autogen/mocs_compilation.o: frdupl_autogen/mocs_compilation.cpp.o

.PHONY : frdupl_autogen/mocs_compilation.o

# target to build an object file
frdupl_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/frdupl_autogen/mocs_compilation.cpp.o
.PHONY : frdupl_autogen/mocs_compilation.cpp.o

frdupl_autogen/mocs_compilation.i: frdupl_autogen/mocs_compilation.cpp.i

.PHONY : frdupl_autogen/mocs_compilation.i

# target to preprocess a source file
frdupl_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/frdupl_autogen/mocs_compilation.cpp.i
.PHONY : frdupl_autogen/mocs_compilation.cpp.i

frdupl_autogen/mocs_compilation.s: frdupl_autogen/mocs_compilation.cpp.s

.PHONY : frdupl_autogen/mocs_compilation.s

# target to generate assembly for a file
frdupl_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/frdupl_autogen/mocs_compilation.cpp.s
.PHONY : frdupl_autogen/mocs_compilation.cpp.s

go_autogen/mocs_compilation.o: go_autogen/mocs_compilation.cpp.o

.PHONY : go_autogen/mocs_compilation.o

# target to build an object file
go_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/go.dir/build.make CMakeFiles/go.dir/go_autogen/mocs_compilation.cpp.o
.PHONY : go_autogen/mocs_compilation.cpp.o

go_autogen/mocs_compilation.i: go_autogen/mocs_compilation.cpp.i

.PHONY : go_autogen/mocs_compilation.i

# target to preprocess a source file
go_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/go.dir/build.make CMakeFiles/go.dir/go_autogen/mocs_compilation.cpp.i
.PHONY : go_autogen/mocs_compilation.cpp.i

go_autogen/mocs_compilation.s: go_autogen/mocs_compilation.cpp.s

.PHONY : go_autogen/mocs_compilation.s

# target to generate assembly for a file
go_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/go.dir/build.make CMakeFiles/go.dir/go_autogen/mocs_compilation.cpp.s
.PHONY : go_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/go.dir/build.make CMakeFiles/go.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/go.dir/build.make CMakeFiles/go.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/go.dir/build.make CMakeFiles/go.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o

.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i

.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s

.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

mytreewidget.o: mytreewidget.cpp.o

.PHONY : mytreewidget.o

# target to build an object file
mytreewidget.cpp.o:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/mytreewidget.cpp.o
.PHONY : mytreewidget.cpp.o

mytreewidget.i: mytreewidget.cpp.i

.PHONY : mytreewidget.i

# target to preprocess a source file
mytreewidget.cpp.i:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/mytreewidget.cpp.i
.PHONY : mytreewidget.cpp.i

mytreewidget.s: mytreewidget.cpp.s

.PHONY : mytreewidget.s

# target to generate assembly for a file
mytreewidget.cpp.s:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/mytreewidget.cpp.s
.PHONY : mytreewidget.cpp.s

progressdialog.o: progressdialog.cpp.o

.PHONY : progressdialog.o

# target to build an object file
progressdialog.cpp.o:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/progressdialog.cpp.o
.PHONY : progressdialog.cpp.o

progressdialog.i: progressdialog.cpp.i

.PHONY : progressdialog.i

# target to preprocess a source file
progressdialog.cpp.i:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/progressdialog.cpp.i
.PHONY : progressdialog.cpp.i

progressdialog.s: progressdialog.cpp.s

.PHONY : progressdialog.s

# target to generate assembly for a file
progressdialog.cpp.s:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/progressdialog.cpp.s
.PHONY : progressdialog.cpp.s

tbufferedreader.o: tbufferedreader.cpp.o

.PHONY : tbufferedreader.o

# target to build an object file
tbufferedreader.cpp.o:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/tbufferedreader.cpp.o
.PHONY : tbufferedreader.cpp.o

tbufferedreader.i: tbufferedreader.cpp.i

.PHONY : tbufferedreader.i

# target to preprocess a source file
tbufferedreader.cpp.i:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/tbufferedreader.cpp.i
.PHONY : tbufferedreader.cpp.i

tbufferedreader.s: tbufferedreader.cpp.s

.PHONY : tbufferedreader.s

# target to generate assembly for a file
tbufferedreader.cpp.s:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/tbufferedreader.cpp.s
.PHONY : tbufferedreader.cpp.s

textviewer.o: textviewer.cpp.o

.PHONY : textviewer.o

# target to build an object file
textviewer.cpp.o:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/textviewer.cpp.o
.PHONY : textviewer.cpp.o

textviewer.i: textviewer.cpp.i

.PHONY : textviewer.i

# target to preprocess a source file
textviewer.cpp.i:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/textviewer.cpp.i
.PHONY : textviewer.cpp.i

textviewer.s: textviewer.cpp.s

.PHONY : textviewer.s

# target to generate assembly for a file
textviewer.cpp.s:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/textviewer.cpp.s
.PHONY : textviewer.cpp.s

trigramsrepository.o: trigramsrepository.cpp.o

.PHONY : trigramsrepository.o

# target to build an object file
trigramsrepository.cpp.o:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/trigramsrepository.cpp.o
.PHONY : trigramsrepository.cpp.o

trigramsrepository.i: trigramsrepository.cpp.i

.PHONY : trigramsrepository.i

# target to preprocess a source file
trigramsrepository.cpp.i:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/trigramsrepository.cpp.i
.PHONY : trigramsrepository.cpp.i

trigramsrepository.s: trigramsrepository.cpp.s

.PHONY : trigramsrepository.s

# target to generate assembly for a file
trigramsrepository.cpp.s:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/trigramsrepository.cpp.s
.PHONY : trigramsrepository.cpp.s

trigramssearcher.o: trigramssearcher.cpp.o

.PHONY : trigramssearcher.o

# target to build an object file
trigramssearcher.cpp.o:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/trigramssearcher.cpp.o
.PHONY : trigramssearcher.cpp.o

trigramssearcher.i: trigramssearcher.cpp.i

.PHONY : trigramssearcher.i

# target to preprocess a source file
trigramssearcher.cpp.i:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/trigramssearcher.cpp.i
.PHONY : trigramssearcher.cpp.i

trigramssearcher.s: trigramssearcher.cpp.s

.PHONY : trigramssearcher.s

# target to generate assembly for a file
trigramssearcher.cpp.s:
	$(MAKE) -f CMakeFiles/frdupl.dir/build.make CMakeFiles/frdupl.dir/trigramssearcher.cpp.s
.PHONY : trigramssearcher.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... go"
	@echo "... frdupl"
	@echo "... go_autogen"
	@echo "... frdupl_autogen"
	@echo "... dirlist.o"
	@echo "... dirlist.i"
	@echo "... dirlist.s"
	@echo "... fileindexer.o"
	@echo "... fileindexer.i"
	@echo "... fileindexer.s"
	@echo "... frdupl_autogen/mocs_compilation.o"
	@echo "... frdupl_autogen/mocs_compilation.i"
	@echo "... frdupl_autogen/mocs_compilation.s"
	@echo "... go_autogen/mocs_compilation.o"
	@echo "... go_autogen/mocs_compilation.i"
	@echo "... go_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... mytreewidget.o"
	@echo "... mytreewidget.i"
	@echo "... mytreewidget.s"
	@echo "... progressdialog.o"
	@echo "... progressdialog.i"
	@echo "... progressdialog.s"
	@echo "... tbufferedreader.o"
	@echo "... tbufferedreader.i"
	@echo "... tbufferedreader.s"
	@echo "... textviewer.o"
	@echo "... textviewer.i"
	@echo "... textviewer.s"
	@echo "... trigramsrepository.o"
	@echo "... trigramsrepository.i"
	@echo "... trigramsrepository.s"
	@echo "... trigramssearcher.o"
	@echo "... trigramssearcher.i"
	@echo "... trigramssearcher.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

